# Generated by Django 5.1.15 on 2026-08-03 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='wholesale_available',
        ),
    ]
