# Generated by Django 5.1.15 on 2026-08-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=230, unique=True)),
                ('description', models.TextField(blank=True)),
                ('discount_percentage', models.PositiveIntegerField(default=0, help_text='Percentage discount applied to the bundle (0-100).')),
                ('image', models.ImageField(blank=True, upload_to='packages/')),
                ('is_active', models.BooleanField(default=True)),
                ('products', models.ManyToManyField(blank=True, help_text='Products included in this bundle.', related_name='packages', to='products.product')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
